name: bmi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.3
  cupertino_icons: ^1.0.8
  animations: ^2.0.11 
  auto_size_text: ^3.0.0
  responsive_framework: ^1.5.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:   # 👈 ye sahi jagah hai (dev_dependencies ke baad)
  android: true
  ios: true
  image_path: "assets/images/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/bmi.png
    - assets/images/girl.png
    - assets/images/menAV.jpg
    - assets/images/girlAV.jpg

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf

    - family: Boldonse
      fonts:
        - asset: assets/fonts/Boldonse.ttf

    - family: Serif
      fonts:
        - asset: assets/fonts/Serif.ttf

    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald.ttf
